import { MENSEI_ULKELER, type MenseiUlke } from './menseiUlkeler';

export { MENSEI_ULKELER, type MenseiUlke };

/** Menşei (ülke) alanı için Türkçe ülke adları listesi. */
export const ULKELER: readonly string[] = [
  'Türkiye',
  'Afganistan',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Andorra',
  'Angola',
  'Antigua ve Barbuda',
  'Arjantin',
  'Arnavutluk',
  'Avustralya',
  'Avusturya',
  'Azerbaycan',
  'Bahamalar',
  'Bahreyn',
  'Bangladeş',
  'Barbados',
  'Belçika',
  'Belize',
  'Benin',
  'Beyaz Rusya',
  'Bhutan',
  'Birleşik Arap Emirlikleri',
  'Birleşik Krallık',
  'Bolivya',
  'Bosna-Hersek',
  'Botsvana',
  'Brezilya',
  'Brunei',
  'Bulgaristan',
  'Burkina Faso',
  'Burundi',
  'Cape Verde',
  'Cezayir',
  'Cibuti',
  'Çad',
  'Çekya',
  'Çin',
  'Danimarka',
  'Dominik Cumhuriyeti',
  'Dominika',
  'Doğu Timor',
  'Ekvador',
  'Ekvator Ginesi',
  'El Salvador',
  'Endonezya',
  'Eritre',
  'Ermenistan',
  'Estonya',
  'Esvatini',
  'Etiyopya',
  'Fas',
  'Fiji',
  'Fildişi Sahili',
  'Filipinler',
  'Filistin',
  'Finlandiya',
  'Fransa',
  'Gabon',
  'Gambiya',
  'Gana',
  'Gine',
  'Gine-Bissau',
  'Grenada',
  'Guatemala',
  'Guyana',
  'Güney Afrika',
  'Güney Kore',
  'Güney Sudan',
  'Gürcistan',
  'Haiti',
  'Hindistan',
  'Hollanda',
  'Honduras',
  'Hırvatistan',
  'Irak',
  'İngiltere',
  'İran',
  'İrlanda',
  'İspanya',
  'İsrail',
  'İsveç',
  'İsviçre',
  'İtalya',
  'İzlanda',
  'Jamaika',
  'Japonya',
  'Kamboçya',
  'Kamerun',
  'Kanada',
  'Karadağ',
  'Katar',
  'Kazakistan',
  'Kenya',
  'Kırgızistan',
  'Kiribati',
  'Kolombiya',
  'Komorlar',
  'Kongo Cumhuriyeti',
  'Kongo Demokratik Cumhuriyeti',
  'Kosova',
  'Kosta Rika',
  'Kuveyt',
  'Kuzey Kore',
  'Kuzey Makedonya',
  'Küba',
  'Laos',
  'Lesotho',
  'Letonya',
  'Liberya',
  'Libya',
  'Liechtenstein',
  'Litvanya',
  'Lübnan',
  'Lüksemburg',
  'Macaristan',
  'Madagaskar',
  'Malavi',
  'Maldivler',
  'Malezya',
  'Mali',
  'Malta',
  'Marshall Adaları',
  'Meksika',
  'Mısır',
  'Mikronezya',
  'Moğolistan',
  'Moldova',
  'Monako',
  'Moritanya',
  'Mauritius',
  'Mozambik',
  'Myanmar',
  'Namibya',
  'Nauru',
  'Nepal',
  'Nijer',
  'Nijerya',
  'Nikaragua',
  'Norveç',
  'Orta Afrika Cumhuriyeti',
  'Özbekistan',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua Yeni Gine',
  'Paraguay',
  'Peru',
  'Polonya',
  'Portekiz',
  'Romanya',
  'Ruanda',
  'Rusya',
  'Saint Kitts ve Nevis',
  'Saint Lucia',
  'Saint Vincent ve Grenadinler',
  'Samoa',
  'San Marino',
  'Sao Tome ve Principe',
  'Senegal',
  'Seyşeller',
  'Sırbistan',
  'Sierra Leone',
  'Singapur',
  'Slovakya',
  'Slovenya',
  'Solomon Adaları',
  'Somali',
  'Sri Lanka',
  'Sudan',
  'Suriye',
  'Suudi Arabistan',
  'Surinam',
  'Şili',
  'Tacikistan',
  'Tanzanya',
  'Tayland',
  'Tayvan',
  'Togo',
  'Tonga',
  'Trinidad ve Tobago',
  'Tunus',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukrayna',
  'Umman',
  'Uruguay',
  'Ürdün',
  'Vanuatu',
  'Vatikan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yeni Zelanda',
  'Yeşil Burun Adaları',
  'Yunanistan',
  'Zambiya',
  'Zimbabve',
];

/** Menşei: 0 = odaklanınca tüm liste; yazarken filtreler. */
export const MIN_ULKE_ARAMA_UZUNLUGU = 0;

/** flagcdn PNG — Windows emoji bayrak göstermediği için. */
export function ulkeBayrakUrl(iso: string, genislik: 20 | 40 | 80 = 40): string {
  return `https://flagcdn.com/w${genislik}/${iso.toLowerCase()}.png`;
}

/** Ülke adına göre ISO2 (büyük/küçük harf duyarsız). */
export function ulkeIsoBul(ad: string): string | undefined {
  const q = ad.trim().toLocaleLowerCase('tr');
  if (!q) return undefined;
  return MENSEI_ULKELER.find((u) => u.ad.toLocaleLowerCase('tr') === q)?.iso;
}

/** Yazılan metni içeren ülkeleri (Türkçe duyarlı) döndürür; boş aramada tüm liste. */
export function ulkeAra(arama: string): Promise<string[]> {
  const q = arama.trim().toLocaleLowerCase('tr');
  const liste = q
    ? MENSEI_ULKELER.filter((u) => u.ad.toLocaleLowerCase('tr').includes(q))
    : MENSEI_ULKELER;
  const adlar = [...new Set(liste.map((u) => u.ad))];
  return Promise.resolve(adlar);
}
