/** Menşei (ülke) alanı için Türkçe ülke adları listesi. */
export const ULKELER: readonly string[] = [
  'Türkiye',
  'Afganistan',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Andorra',
  'Angola',
  'Antigua ve Barbuda',
  'Arjantin',
  'Arnavutluk',
  'Avustralya',
  'Avusturya',
  'Azerbaycan',
  'Bahamalar',
  'Bahreyn',
  'Bangladeş',
  'Barbados',
  'Belçika',
  'Belize',
  'Benin',
  'Beyaz Rusya',
  'Bhutan',
  'Birleşik Arap Emirlikleri',
  'Birleşik Krallık',
  'Bolivya',
  'Bosna-Hersek',
  'Botsvana',
  'Brezilya',
  'Brunei',
  'Bulgaristan',
  'Burkina Faso',
  'Burundi',
  'Cape Verde',
  'Cezayir',
  'Cibuti',
  'Çad',
  'Çekya',
  'Çin',
  'Danimarka',
  'Dominik Cumhuriyeti',
  'Dominika',
  'Doğu Timor',
  'Ekvador',
  'Ekvator Ginesi',
  'El Salvador',
  'Endonezya',
  'Eritre',
  'Ermenistan',
  'Estonya',
  'Esvatini',
  'Etiyopya',
  'Fas',
  'Fiji',
  'Fildişi Sahili',
  'Filipinler',
  'Filistin',
  'Finlandiya',
  'Fransa',
  'Gabon',
  'Gambiya',
  'Gana',
  'Gine',
  'Gine-Bissau',
  'Grenada',
  'Guatemala',
  'Guyana',
  'Güney Afrika',
  'Güney Kore',
  'Güney Sudan',
  'Gürcistan',
  'Haiti',
  'Hindistan',
  'Hollanda',
  'Honduras',
  'Hırvatistan',
  'Irak',
  'İngiltere',
  'İran',
  'İrlanda',
  'İspanya',
  'İsrail',
  'İsveç',
  'İsviçre',
  'İtalya',
  'İzlanda',
  'Jamaika',
  'Japonya',
  'Kamboçya',
  'Kamerun',
  'Kanada',
  'Karadağ',
  'Katar',
  'Kazakistan',
  'Kenya',
  'Kırgızistan',
  'Kiribati',
  'Kolombiya',
  'Komorlar',
  'Kongo Cumhuriyeti',
  'Kongo Demokratik Cumhuriyeti',
  'Kosova',
  'Kosta Rika',
  'Kuveyt',
  'Kuzey Kore',
  'Kuzey Makedonya',
  'Küba',
  'Laos',
  'Lesotho',
  'Letonya',
  'Liberya',
  'Libya',
  'Liechtenstein',
  'Litvanya',
  'Lübnan',
  'Lüksemburg',
  'Macaristan',
  'Madagaskar',
  'Malavi',
  'Maldivler',
  'Malezya',
  'Mali',
  'Malta',
  'Marshall Adaları',
  'Meksika',
  'Mısır',
  'Mikronezya',
  'Moğolistan',
  'Moldova',
  'Monako',
  'Moritanya',
  'Mauritius',
  'Mozambik',
  'Myanmar',
  'Namibya',
  'Nauru',
  'Nepal',
  'Nijer',
  'Nijerya',
  'Nikaragua',
  'Norveç',
  'Orta Afrika Cumhuriyeti',
  'Özbekistan',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua Yeni Gine',
  'Paraguay',
  'Peru',
  'Polonya',
  'Portekiz',
  'Romanya',
  'Ruanda',
  'Rusya',
  'Saint Kitts ve Nevis',
  'Saint Lucia',
  'Saint Vincent ve Grenadinler',
  'Samoa',
  'San Marino',
  'Sao Tome ve Principe',
  'Senegal',
  'Seyşeller',
  'Sırbistan',
  'Sierra Leone',
  'Singapur',
  'Slovakya',
  'Slovenya',
  'Solomon Adaları',
  'Somali',
  'Sri Lanka',
  'Sudan',
  'Suriye',
  'Suudi Arabistan',
  'Surinam',
  'Şili',
  'Tacikistan',
  'Tanzanya',
  'Tayland',
  'Tayvan',
  'Togo',
  'Tonga',
  'Trinidad ve Tobago',
  'Tunus',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukrayna',
  'Umman',
  'Uruguay',
  'Ürdün',
  'Vanuatu',
  'Vatikan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yeni Zelanda',
  'Yeşil Burun Adaları',
  'Yunanistan',
  'Zambiya',
  'Zimbabve',
];

/** Menşei aramasında en az bu kadar harf yazılınca öneri gösterilir. */
export const MIN_ULKE_ARAMA_UZUNLUGU = 1;

const ULKE_ONERI_LIMIT = 30;

/** Yazılan metni içeren ülkeleri (Türkçe duyarlı) döndürür. */
export function ulkeAra(arama: string): Promise<string[]> {
  const q = arama.trim().toLocaleLowerCase('tr');
  const liste = q
    ? ULKELER.filter((u) => u.toLocaleLowerCase('tr').includes(q))
    : [...ULKELER];
  return Promise.resolve(
    liste.sort((a, b) => a.localeCompare(b, 'tr')).slice(0, ULKE_ONERI_LIMIT)
  );
}
