import type { AdminCari } from '@/admin/baslat-menusu/erp/cari/tipler';

/** Deneme / offline başlangıç cari kayıtları */
export function cariSeedKayitlari(simdi: string): AdminCari[] {
  return [
    {
      id: '1',
      firmaId: '1',
      ustId: '',
      cariTipi: 'SATICI',
      isletmeTuru: 'TUZEL',
      cariKodu: 'S.07.0001',
      cariAdi: 'GUZEL TEKNOLOJI',
      unvan: 'GUZEL IC VE DIS TICARET LIMITED SIRKETI',
      fiyatTanimi: 'FIYAT',
      yetkili: 'ERCAN GUZEL',
      vergiDairesi: 'ANTALYA KURUMLAR',
      vergiNo: '9250508945',
      il: 'ANTALYA',
      ilce: 'KEPEZ',
      adres: 'YENI EMEK MAH. YILDIRIM BEYAZIT CAD. NO:130A',
      telefon: '+90 850 885 11 60',
      gsm: '',
      eposta: 'bilgi@guzelteknoloji.com',
      web: 'www.guzelteknoloji.com',
      efatura: true,
      earsiv: true,
      efaturaTipi: 'TICARI',
      alias: 'urn:mail:defaultpk@guzelteknoloji.com',
      earsivAlias: 'urn:mail:defaultgb@guzelteknoloji.com',
      earsivTeslimSekli: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '2',
      firmaId: '1',
      ustId: '',
      cariTipi: 'ALICI',
      isletmeTuru: 'GERCEK',
      cariKodu: 'A.07.0001',
      cariAdi: 'ERCAN GUZEL',
      unvan: 'ERCAN GUZEL',
      fiyatTanimi: 'FIYAT',
      yetkili: 'ERCAN GUZEL',
      vergiDairesi: '',
      vergiNo: '12345678901',
      il: 'ANTALYA',
      ilce: 'KEPEZ',
      adres: 'KUTUKCU MAH. 2979 SOK. NO:4 DAIRE:5',
      telefon: '5325674660',
      gsm: '',
      eposta: 'bilgi@ercanguzel.com',
      web: 'www.ercanguzel.com',
      efatura: false,
      earsiv: true,
      efaturaTipi: 'TEMEL',
      alias: '',
      earsivAlias: 'urn:mail:earsiv@ercanguzel.com',
      earsivTeslimSekli: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '3',
      firmaId: '1',
      ustId: '',
      cariTipi: 'ALICI',
      isletmeTuru: 'TUZEL',
      cariKodu: 'A.06.0012',
      cariAdi: 'ANADOLU POS AS',
      unvan: 'ANADOLU POS ANONIM SIRKETI',
      fiyatTanimi: 'FIYAT',
      yetkili: 'AYSE YILMAZ',
      vergiDairesi: 'KADIKOY',
      vergiNo: '1234567890',
      il: 'ISTANBUL',
      ilce: 'KADIKOY',
      adres: 'CAFERAGA MAH. MODA CAD. NO:18',
      telefon: '2165550101',
      gsm: '',
      eposta: 'info@anadolupos.com',
      web: 'www.anadolupos.com',
      efatura: true,
      earsiv: false,
      efaturaTipi: 'TICARI',
      alias: '',
      earsivAlias: '',
      earsivTeslimSekli: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '4',
      firmaId: '1',
      ustId: '',
      cariTipi: 'SATICI',
      isletmeTuru: 'TUZEL',
      cariKodu: 'S.34.0044',
      cariAdi: 'DELTA YAZILIM',
      unvan: 'DELTA YAZILIM VE DANISMANLIK LTD STI',
      fiyatTanimi: 'FIYAT',
      yetkili: 'MEHMET KAYA',
      vergiDairesi: 'SISLI',
      vergiNo: '6080123456',
      il: 'ISTANBUL',
      ilce: 'SISLI',
      adres: 'HALASKARGAZI CAD. NO:220 KAT:3',
      telefon: '2125558899',
      gsm: '',
      eposta: 'destek@deltayazilim.com',
      web: 'www.deltayazilim.com',
      efatura: true,
      earsiv: true,
      efaturaTipi: 'TEMEL',
      alias: '',
      earsivAlias: '',
      earsivTeslimSekli: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '5',
      firmaId: '1',
      ustId: '',
      cariTipi: 'ALICI',
      isletmeTuru: 'YABANCI',
      cariKodu: 'A.00.0008',
      cariAdi: 'JOHN SMITH TRADING',
      unvan: 'JOHN SMITH TRADING LLC',
      fiyatTanimi: 'FIYAT',
      yetkili: 'JOHN SMITH',
      vergiDairesi: '',
      vergiNo: 'P99887766',
      il: 'ANKARA',
      ilce: 'CANKAYA',
      adres: 'KIZILAY MAH. ATLAS CAD. NO:12',
      telefon: '3125554411',
      gsm: '',
      eposta: 'john@smithtrading.com',
      web: '',
      efatura: false,
      earsiv: false,
      efaturaTipi: 'TEMEL',
      alias: '',
      earsivAlias: '',
      earsivTeslimSekli: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '6',
      firmaId: '1',
      ustId: '',
      cariTipi: 'ALICI',
      isletmeTuru: 'GERCEK',
      cariKodu: 'A.07.0099',
      cariAdi: 'ZEYNEP DEMIR',
      unvan: 'ZEYNEP DEMIR',
      fiyatTanimi: 'FIYAT',
      yetkili: 'ZEYNEP DEMIR',
      vergiDairesi: '',
      vergiNo: '98765432109',
      il: 'ANTALYA',
      ilce: 'MURATPASA',
      adres: 'FENER MAH. 1968 SOK. NO:7',
      telefon: '5051112233',
      gsm: '',
      eposta: 'zeynep.demir@mail.com',
      web: '',
      efatura: false,
      earsiv: false,
      efaturaTipi: 'TEMEL',
      alias: '',
      earsivAlias: '',
      earsivTeslimSekli: '',
      aktif: false,
      olusturma: simdi,
      guncelleme: simdi,
    },
  ];
}
