import type { AdminCari } from '@/admin/baslat-menusu/erp/cari/tipler';

/** backend/prisma/seed.ts — f001cariler ile birebir uyumlu baslangic verisi */
export function cariSeedKayitlari(simdi: string): AdminCari[] {
  return [
    {
      id: '1',
      firmaId: '1',
      ustId: '',
      cariTipi: 'SATICI',
      isletmeTuru: 'TUZEL',
      cariKodu: 'S.07.0001',
      cariAdi: 'GUZEL TEKNOLOJI',
      unvan: 'GUZEL IC VE DIS TICARET LIMITED SIRKETI',
      yetkili: 'ERCAN GUZEL',
      vergiDairesi: 'ANTALYA KURUMLAR',
      vergiNo: '9250508945',
      il: 'ANTALYA',
      ilce: 'KEPEZ',
      adres: 'YENI EMEK MAH. YILDIRIM BEYAZIT CAD. NO:130A',
      telefon: '8508851160',
      eposta: 'bilgi@guzelteknoloji.com',
      web: 'www.guzelteknoloji.com',
      efatura: true,
      efaturaTipi: 'TICARI FATURA',
      alias: 'urn:mail:defaultpk@guzelteknoloji.com',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
    {
      id: '2',
      firmaId: '1',
      ustId: '',
      cariTipi: 'ALICI',
      isletmeTuru: 'GERCEK',
      cariKodu: 'A.07.0001',
      cariAdi: 'ERCAN GUZEL',
      unvan: 'ERCAN GUZEL',
      yetkili: 'ERCAN GUZEL',
      vergiDairesi: 'TC',
      vergiNo: '',
      il: 'ANTALYA',
      ilce: 'KEPEZ',
      adres: 'KUTUKCU MAH. 2979 SOK. NO:4 DAIRE:5',
      telefon: '5325674660',
      eposta: 'bilgi@ercanguzel.com',
      web: 'www.ercanguzel.com',
      efatura: false,
      efaturaTipi: 'E-ARSIV',
      alias: '',
      aktif: true,
      olusturma: simdi,
      guncelleme: simdi,
    },
  ];
}
